version: "3.8"
services:
  api:
    container_name: rust-on-docker-lambda
    build: .
    ports:
      - "8081:8080"
    environment:
      - RUST_LOG=debug
      - AWS_ACCESS_KEY_ID=dummy-access-key-id
      - AWS_SECRET_ACCESS_KEY=dummy-secret-key
      - AWS_SESSION_TOKEN=dummy-ssession-token
